### ISSUE TITLE
2D Band and spin texture

### ISSUE THREAD

**Issue by kashikarravi** [hungpham2017/mcu#10]
Hi,

First of all, thank you for developing the mcu. I am using mcu, it's really nice and has good features. 

I have few questions.

1. Am I able to plot a particular band in a 2D plane? Right now it is offering me both CB and VB. In my case both are far away from each other, so they are looking flat in nature. Or it is possible to set the energy range. 
2. Is it possible to plot the spin texture on the 2D bands? As both are using the same modules. 
3. How to obtain data files from each calculation, so that I can use other sources to plot them?

**Comment by hungpham2017** [comment]
Sorry, I was planning to respond then forget since I am transitioning to a new HPC system. Did you figure it out or you still need support?

**Comment by kashikarravi** [comment]
Thank you, Hung. Ya, I resolved all the issues. The filter option helped me a lot.

**Comment by hungpham2017** [comment]
great!
