### ISSUE TITLE
bug: AttributeError: module 'mcu' has no attribute 'VASP'

### ISSUE THREAD

**Issue by pjwangpku** [hungpham2017/mcu#14]
I used the code "$ git clone https://github.com/hungpham2017/mcu" to install mcu in the server with VASP and python on it. Then when I ran the code for plotting: 
import mcu
import matplotlib.pyplot as plt
mymcu = mcu.VASP()

mymcu.plot_dos(spin='updown', style=1, efermi=5.0705, lm=['Ga:p','N:px'], elim=[-6, 8],yscale=0.05, save=True,fontsize=10, figname='Ga_updown', dpi=300)

plt.show()

It always shows "Traceback (most recent call last):
  File "/vol01/homes/hy29793/SiC/mcuplot.py", line 3, in <module>
    mymcu = mcu.VASP()
AttributeError: module 'mcu' has no attribute 'VASP'
"

The code in the tutorial also used "import mcu
 mymcu = mcu.VASP()".

What is the problem here and how to solve it?

**Comment by MichealWangYZ** [comment]
Hi,

I also have encountered such kind of issues, especially on WSL. Is this also the case for you? I think it works well for Mac tho.

**Comment by hungpham2017** [comment]
Must the an error due to wrong PYTHONPATH.

pip and conda install are available. Please install the latest version by:

`pip install mcu`

or for macOS:

`conda install -c hqp mcu`
