### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by MichealWangYZ** [hungpham2017/mcu#15]
Hi!

I'm not familiar with your Apache License, but in our upcoming publication I used your code to plot DOS and bands. So I can I cite it?

Yizhou

**Comment by hungpham2017** [comment]
Thanks for using the code. Something like this (ACS convention) should be sufficient: 
Pham, H. Q. MCU: Modeling and Crystallographic Utilities, 2023 https://github.com/hungpham2017/mcu (**accessed Feb, 14, 2023**).

**Comment by MichealWangYZ** [comment]
Thank you!
