### ISSUE TITLE
NameError in pywannier90_vasp.py

### ISSUE THREAD

**Issue by houzf** [hungpham2017/mcu#7]
In the following line of "mcu/wannier90/pywannier90_vasp.py"
----------------------------------------
 616               unk = self.wave.get_unk(spin=self.spin, kpt=k_id+1, band=n+1, ngrid=ngrid)
----------------------------------------
"n" and "ngrid" aren't defined before they are assgined to "band" and "ngrid", respectively.
It seems that this line should be corrected as:
unk = self.wave.get_unk(spin=self.spin, kpt=k_id+1, band=band+1,ngrid=grid)

After the above modification, it caused the following error:
 line 634, in export_AME
    self.export_unk(self, grid = grid)
TypeError: export_unk() got multiple values for argument 'grid'

Please check it.

**Comment by hungpham2017** [comment]
Thank you for the bug report. Indeed, these bugs were fixed in my local version which includes bug fixed and new functions.
I am still in the process of extending the code to the non-collinear wave function. As long as this is done (hopefully in 1-2 weeks), we can pull the new version to MCU.

**Comment by hungpham2017** [comment]
The bug should be fixed now in the dev branch. pyWannier90 now works for the spinor wave function in a non-collinear calculation.
However, spatial symmetry is not supported currently (i.e., only ISYM=-1 and ISYM=0 are allowed). I will close this issue if there is no more question.
